### PR TITLE
Updated the example of tailRec

### PR DESCRIPTION
**Pull request by jmgimeno**
The given example in the comment about tailRec has been adapted to the new implementation.

### CODE REVIEW

**Comment by jmgimeno** [comment]
I didn't adapted the example in the comment about tailRec in the previous commit. Sorry to have missed that.

**Review by daniel-ciocirlan — APPROVED** [review]
Makes sense.

**Comment by jmgimeno** [comment]
Is there anything more that I must do?

**Comment by daniel-ciocirlan** [comment]
Forgot to merge.

**Pull request merged**
